#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------


namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Media {
                namespace Animation {
                    ref class Storyboard;
                }
            }
        }
    }
}
namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class StackPanel;
                ref class TextBox;
                ref class Button;
                ref class Image;
            }
        }
    }
}

namespace Chat_uwp
{
    [::Windows::Foundation::Metadata::WebHostHidden]
    partial ref class AddStatusUC : public ::Windows::UI::Xaml::Controls::UserControl, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector,
        public ::Windows::UI::Xaml::Markup::IComponentConnector2
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
        virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
    
    private:
        void UnloadObject(::Windows::UI::Xaml::DependencyObject^ dependencyObject);
        void DisconnectUnloadedObject(int connectionId);
    
    private:
        bool _contentLoaded;
    
        class AddStatusUC_obj1_Bindings;
    
        private: ::Windows::UI::Xaml::Media::Animation::Storyboard^ Storyboard1;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ stackPanel;
        private: ::Windows::UI::Xaml::Controls::TextBox^ statusTxt_txt;
        private: ::Windows::UI::Xaml::Controls::Button^ Add_btn;
        private: ::Windows::UI::Xaml::Controls::Button^ addImage_btn;
        private: ::Windows::UI::Xaml::Controls::Button^ load_btn;
        private: ::Windows::UI::Xaml::Controls::Image^ image_image;
    };
}

