#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------


namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class ScrollViewer;
                ref class TextBox;
                ref class Button;
                ref class StackPanel;
                ref class TextBlock;
                ref class Image;
            }
        }
    }
}

namespace Chat_uwp
{
    [::Windows::Foundation::Metadata::WebHostHidden]
    partial ref class TextSpace : public ::Windows::UI::Xaml::Controls::UserControl, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector,
        public ::Windows::UI::Xaml::Markup::IComponentConnector2
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
        virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
    
    private:
        void UnloadObject(::Windows::UI::Xaml::DependencyObject^ dependencyObject);
        void DisconnectUnloadedObject(int connectionId);
    
    private:
        bool _contentLoaded;
    
        class TextSpace_obj1_Bindings;
    
        private: ::Windows::UI::Xaml::Controls::ScrollViewer^ scroller_chat;
        private: ::Windows::UI::Xaml::Controls::TextBox^ message_txt;
        private: ::Windows::UI::Xaml::Controls::Button^ send_btn;
        private: ::Windows::UI::Xaml::Controls::Button^ undo_btn;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ messages_pnl;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ name_lbl;
        private: ::Windows::UI::Xaml::Controls::Image^ image_image;
    };
}

